### ISSUE TITLE
Array diff ignores updates to items

### ISSUE THREAD

**Issue by xnejp03** [gnieh/diffson#76] opened 2018-06-27 15:42 UTC
Hi,

it looks like (at least when I'm using my own LCS implementation) the update diff is not processed in the array diff. When I remove an item and also update on of the remaining ones, I'm only getting back the remove operation.

You can see that my LCS uses the `id` field as the unique key.

```scala
import gnieh.diffson.{Lcs, Patience}
import play.api.libs.json.JsValue
import gnieh.diffson.playJson._

object Test extends App {

  object MyJsonDiff extends JsonDiff(new IdentifierLcs(new Patience[IdentifierWrapper]()))


  val item1 = """{"id":"1", "foo": "bar1"}"""
  val item2 = """{"id":"2", "foo": "bar2"}"""
  val item3 = """{"id":"3", "foo": "bar3"}"""
  val item3Updated = """{"id":"3", "foo": "bar4"}"""

  val list1 = s"[$item1,$item2,$item3]"
  val list2 = s"[$item1,$item3Updated]"

  val diff = MyJsonDiff.diff(list1, list2, true)

  println(diff)

  class IdentifierLcs(delegate: Lcs[IdentifierWrapper]) extends Lcs[JsValue] {
    override def lcs(seq1: Seq[JsValue], seq2: Seq[JsValue], low1: Int, high1: Int, low2: Int, high2: Int): List[(Int, Int)] = {
      delegate.lcs(seq1.map(x => new IdentifierWrapper(x)), seq2.map(x => new IdentifierWrapper(x)), low1, high1, low2, high2)
    }
  }

  class IdentifierWrapper(val value: JsValue) {

    import play.api.libs.json._

    override val hashCode: Int = identifierHash(value)

    override def equals(other: Any): Boolean = other match {
      case that: IdentifierWrapper => that.hashCode == hashCode
      case _ => false
    }

    private def identifierHash(v: JsValue): Int = {
      v match {
        case o: JsObject =>
          (o \ "id").get.as[String].hashCode
        case x => x.hashCode()
      }
    }
  }

}
```

This produces:
```
[ {
  "op" : "remove",
  "path" : "/1",
  "old" : {
    "id" : "2",
    "foo" : "bar2"
  }
} ]
```

I'd expect to run the add/remove logic on the array items and then run `diff` on all the remaining items (whose index might have changed now) to get something like (not sure if the index of the replace op should be source or target index):
```
[ {
  "op" : "remove",
  "path" : "/1",
  "old" : {
    "id" : "2",
    "foo" : "bar2"
  }
},
 {
  "op" : "replace",
  "path" : "/1/foo",
  "value": "bar4"
  "old" : "bar3"
}]
```

**Comment by satabin** [comment] 2018-06-28 07:19
After a few tests, it seems that the problem is in your Lcs implementation (standard Lcs works as expected as far as I can tell), I will look at it closer.

Just to be sure I understand your intent: you want to base the Lcs on the sole _id_ value in object, right?

**Comment by xnejp03** [comment] 2018-06-28 08:08
Yes, I have a Json with an array field. the items of the array have `id` and other attributes. I want to be able to see the delta of the array if I add / remove / update an item as a whole.

Basically I want to be able to work out a delta change to the array. It should register the operation of an item being removed or added as a whole, as well as changes to an existing item (identified by the `id`).

**Comment by satabin** [comment] 2018-06-28 08:24
I understand where the problem lies. In the `equals` method you only compare the hashCode, hence only the `id` value in your case. So following objects are considered equal in your class:

```json
{
  "id": 1,
  "value": "test"
}
```

and

```json
{
  "id": 1,
  "value": "new"
}
```

Your `equals` method must, at some point check for real equality to determine whether value changed or not.

From what I understand, you would like to inhibit the recursive diff for elements inside an array. This is not possible in the current implementation of diffson. This behavior seems to be really specific for your use case, and I don’t want to include it as such in diffson. But I can think about a more generic and general way to make diff computation configurable.

**Comment by xnejp03** [comment] 2018-06-28 08:30
I would have thought it does the diff on array items: https://github.com/gnieh/diffson/blob/master/core/src/main/scala/gnieh/diffson/JsonDiffSupport.scala#L174

In any case, is there something I can do now (like fix the `equals`) or is it a dead end?

**Comment by satabin** [comment] 2018-06-28 08:35
Actually, I do not see any way to see objects as a whole. You can fix the `equals` method by comparing the values like this:

```scala
override def equals(other: Any): Boolean = other match {
  case that: IdentifierWrapper => that.value == value                                                                                                                                                      
  case _                                  => false
}
```

But the behavior will be as the standard one as far as I can tell.

Diffson performs structural diff, without any applicative knowledge.
I will think about a way to configure diffs in a more fine-grained fashion, and make a proposal in another issue, but I am afraid what you want to achieve is too specific to have a nice generic solution.

**Comment by satabin** [comment] 2018-10-09 22:17
Closing it as I think this is solved. Re-open it if you still encounter a problem.

**Closed by satabin** 2018-10-09 22:17 UTC
